# DON'T TOUCH THIS!
config-version: 1.0

# ONLY AVAILABLE eng AND ind
# eng -> English
# ind -> Indonesian
default-lang: "eng"

settings:
  vanished-message: true
  join-message: "&a[+] &7{PLAYER} &ajoined"
  quit-message: "&c[+] &7{PLAYER} &cquit"

# YOU CAN CUSTOM THIS!
message:
  eng:
    vanish-enabled: "&aVanish mode enabled"
    vanish-enabled-other1: "&aVanish mode enabled by {PLAYER}"
    vanish-enabled-other2: "&aVanish mode enabled to {PLAYER}"
    vanish-disabled: "&cVanish mode disabled"
    vanish-disabled-other1: "&cVanish mode disabled by {PLAYER}"
    vanish-disabled-other2: "&cVanish mode disabled to {PLAYER}"
  ind:
    vanish-enabled: "&aVanish mode diaktifkan"
    vanish-enabled-other1: "&aVanish mode diaktifkan oleh {PLAYER}"
    vanish-enabled-other2: "&aVanish mode diaktifkan ke {PLAYER}"
    vanish-disabled: "&cVanish mode dimatikan"
    vanish-disabled-other1: "&cVanish mode dimatikan oleh {PLAYER}"
    vanish-disabled-other2: "&cVanish mode dimatikan ke {PLAYER}"